fix: add message when unsubscribe status is pending
snapshot-labs/envelop-ui pull request #3
Opened 2023-03-28 18:19 UTC by wa0x6e

Add a message while the unsubscribing request is processing, in case request is taking a long time

2023-05-11 20:50 UTC, wa0x6e commented
Obsolete feature

2023-05-24 12:24 UTC, Todmy requested changes

2023-05-24 12:24 UTC, Todmy commented on src/views/Home.vue
> +  <div :class="['max-w-screen-xs', 'xs:w-[420px]', 'p-5', 'py-6', { 'text-center': true }]">
```suggestion
  <div class='max-w-screen-xs xs:w-[420px] p-5 py-6 text-center">
```

2023-05-24 12:24 UTC, Todmy commented on src/views/Verify.vue
> +async function verify() {
we can [use](https://vueuse.org/core/useFetch/#usefetch) `useFetch` instead

2023-05-24 12:28 UTC, Todmy commented
also, subscriptions on the `unsubscribe page` subscriptions are not properly defined from the user profile(DB). If a user subscribed to one type of email, the page displays that he/she subscribed to all types.

2023-05-24 13:49 UTC, wa0x6e commented on src/views/Verify.vue
> +async function verify() {
Weird, should already be present: https://github.com/snapshot-labs/envelop-ui/blob/unsubscribe-message/src/views/Verify.vue#LL25C1-L25C1

2023-05-24 14:09 UTC, wa0x6e commented
> also, subscriptions on the unsubscribe page subscriptions are not properly defined from the user profile(DB). If a user subscribed to one type of email, the page displays that he/she subscribed to all types.

Seems like loading the user's existing subscription is not in the scope of this PR. And there are no endpoint on the BE that can return such list, only available endpoint now only return a list by address, and not by email.

Should we go with this PR as is, and implement that feature in another PR, or do it inside this one?

2023-05-24 14:17 UTC, Todmy commented
> > also, subscriptions on the unsubscribe page subscriptions are not properly defined from the user profile(DB). If a user subscribed to one type of email, the page displays that he/she subscribed to all types.
> 
> Seems like loading the user's existing subscription is not in the scope of this PR. And there are no endpoint on the BE that can return such list, only available endpoint now only return a list by address, and not by email.
> 
> Should we go with this PR as is, and implement that feature in another PR, or do it inside this one?

but we have [it](https://github.com/snapshot-labs/envelop/blob/main/src/rpc.ts#L76)

2023-05-24 14:19 UTC, wa0x6e commented
> > also, subscriptions on the unsubscribe page subscriptions are not properly defined from the user profile(DB). If a user subscribed to one type of email, the page displays that he/she subscribed to all types.
> 
> Seems like loading the user's existing subscription is not in the scope of this PR. And there are no endpoint on the BE that can return such list, only available endpoint now only return a list by address, and not by email.
> 
> Should we go with this PR as is, and implement that feature in another PR, or do it inside this one?

This one is for subscriptions by wallet address. The page from envelop-ui requires a list by email address, and it will affects all wallet addresses related to this email.

2023-05-24 17:27 UTC, wa0x6e commented on src/views/Verify.vue
> +async function verify() {
We can, but is it providing additional value from the native `fetch` ? The coding guideline is advocating to use as less dependencies as possible.

2023-05-25 09:47 UTC, wa0x6e commented
> This one is for subscriptions by wallet address. The page from envelop-ui requires a list by email address, and it will affects all wallet addresses related to this email.

I've opened #7 for this

2023-05-27 23:27 UTC, wa0x6e commented on src/views/Verify.vue
> +async function verify() {
Added

2023-05-27 23:33 UTC, wa0x6e commented on src/views/Verify.vue
> +async function verify() {
Only migrated the code in `verify`, `unsubscribe` has been migrated via #8

2023-05-29 16:13 UTC, Todmy approved these changes
tACK

2023-05-29 16:23 UTC, merged